//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.18 at 07:56:39 PM CEST 
//


package org.audiveris.proxymusic.opus;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.audiveris.proxymusic.opus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Opus_QNAME = new QName("", "opus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.audiveris.proxymusic.opus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Opus }
     * 
     */
    public Opus createOpus() {
        return new Opus();
    }

    /**
     * Create an instance of {@link Score }
     * 
     */
    public Score createScore() {
        return new Score();
    }

    /**
     * Create an instance of {@link OpusLink }
     * 
     */
    public OpusLink createOpusLink() {
        return new OpusLink();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Opus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "opus")
    public JAXBElement<Opus> createOpus(Opus value) {
        return new JAXBElement<Opus>(_Opus_QNAME, Opus.class, null, value);
    }

}
