
package org.audiveris.proxymusic.util;

/** 
 * Class {@code ProgramId} provides full program identification.
 * This code is generated by an Ant target using Hg information.
 */
public class ProgramId 
{
    /** Precise program name: {@value} */
    public static final java.lang.String NAME = "ProxyMusic";

    /** Precise program version: {@value} */
    public static final java.lang.String VERSION = "3.0.1";

    /** Precise program revision: {@value} */
    public static final java.lang.String REVISION = "8e1a2c5";
}
        